display_name: Hawk VPN
package_name: hawk-vpn
maintainer:
  name: chen08209
  email: chen08209@gmail.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev

keywords:
  - Hawk VPN
  - Clash
  - ClashMeta
  - Proxy

generic_name: Hawk VPN

categories:
  - Network

startup_notify: true
